<?php

namespace UtilisateursBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function byMail()
    {
        $rep      = $this->createQueryBuilder('u');
        $rep->select('u.emailCanonical');
        $rep->where('u.enabled = :true' );
        $rep->setParameter('true', 1);

        $repo     = $rep->getQuery();
        return	$repo->getResult();
    }

}
