pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

adminproduits:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing/produits.yml"
    prefix:   /admin/produits

admincommandes:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing/commandes.yml"
    prefix:   /admin/commandes

ecommerce_ecommerce:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

admincategories:
    resource: "@EcommerceEcommerceBundle/Resources/config/routing/categories.yml"
    prefix:   /admin/categories


#ecommerce:
 #   resource: "@EcommerceBundle/Resources/config/routing.yml"
  #  prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"