<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
  
  public function monArray($montab)
  {
    $rep      = $this->createQueryBuilder('p');
                $rep->Select('p');
                $rep->Where('p.id IN (:array)'); // On met IN parce que c'est un tableau qu'on passe
                $rep->setParameter('array', $montab);

                $repo     = $rep->getQuery();
    return  $repo->getResult();

  }


	public function categ($category)
	{
		$rep      = $this->createQueryBuilder('p');
		            $rep->select('p');			
                    $rep->where('p.categorie = :categorie' );
                    $rep->andWhere('p.disponible=1');
                    $rep->setParameter('categorie', $category);

               /*     $rep->where('a.author = :author')
       ->setParameter('author', $author)
     ->andWhere('a.date < :year')
       ->setParameter('year', $year)
     ->orderBy('a.date', 'DESC')
  ;
*/

		$repo     = $rep->getQuery();
	return	$repo->getResult();
    }

/*
public function myFindAll()
{
  return $this
    ->createQueryBuilder('a')
    ->getQuery()
    ->getResult()
  ;
}
*/

public function recherche($recherche) 
    {
         $rep   = $this->createQueryBuilder('p');
                $rep->select('p');      
                $rep->where('p.nom like :marecherche' );
                $rep->andWhere('p.disponible=1');
                $rep->setParameter('marecherche', $recherche);
          $repo     = $rep->getQuery();
          return  $repo->getResult();
    }
	
}
